with open("mynewtextfile.txt","w+") as f:
    f.writelines("\nOtus we are learning python\nOtus we are learning python\nOtus we are learning python")
    f.seek(0)
    print(f.readlines())
    print("Is readable:", f.readable())
    print("Is writeable:", f.writable())
    print("File no:", f.fileno())
    print("Is connected to tty-like device:", f.isatty())
    f.truncate(20)
    f.flush()
    f.seek(0)
    print(f.readline())
    print(f.readline())
    print(f.readline())
    print(f.readline())
    print(f.readline())
f.close()